"""
Postmaster — Centralized Email Formatting & Delivery
=====================================================
Single source of truth for all email styling, templates, and delivery.

Report generators own CONTENT (what data, which sections).
Postmaster owns PRESENTATION (colors, fonts, document shell, delivery).

ALL email formatting and sending MUST go through this module.
See CLAUDE.md "Email Routing" section for the routing rule.

Usage:
    from .postmaster import CLR_GREEN, CLR_RED, wrap_document, send_email

    # Simple: pass markdown
    html = markdown_to_html("# Report\\n| A | B |\\n|---|---|\\n| 1 | 2 |")
    send_email("Subject", html)

    # Advanced: build sections yourself, wrap in standard shell
    sections_html = my_custom_table_builder(data)
    html = wrap_document(sections_html, title="My Report", subtitle="Feb 27")
    send_email("Subject", html)
"""

import logging
import os
import re
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

log = logging.getLogger("nenner")

# ---------------------------------------------------------------------------
# Canonical Color Palette — change here, changes everywhere
# ---------------------------------------------------------------------------

FONT = ("-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, "
        "'Helvetica Neue', Arial, sans-serif")

# Core layout
CLR_BG       = "#ffffff"    # Body background — white per user directive
CLR_WHITE    = "#ffffff"    # Card / content background
CLR_HEADER   = "#1e293b"    # Dark slate — header banner, titles
CLR_TEXT     = "#1e293b"    # Primary text color — black/dark
CLR_MUTED    = "#64748b"    # Secondary / footnote text
CLR_BORDER   = "#1e293b"    # Borders and dividers — black
CLR_ROW_ALT  = "#f8fafc"    # Alternating table row background

# Semantic colors
CLR_GREEN       = "#16a34a"   # Profit, BUY
CLR_RED         = "#dc2626"   # Loss, SELL
CLR_AMBER       = "#f59e0b"   # Warning, watch
CLR_PURPLE      = "#7c3aed"   # Reversal
CLR_BLUE        = "#3b82f6"   # Info, accent

# Light backgrounds (alert boxes)
CLR_LIGHT_RED    = "#fef2f2"
CLR_LIGHT_AMBER  = "#fffbeb"
CLR_LIGHT_PURPLE = "#f5f3ff"
CLR_LIGHT_GREEN  = "#f0fdf4"


# ---------------------------------------------------------------------------
# Document Shell
# ---------------------------------------------------------------------------

def wrap_document(
    body_html: str,
    title: str = "",
    subtitle: str = "",
    footer_text: str = "Generated by Stanley | NennerEngine Trading Desk",
    max_width: int = 680,
    notes_html: str = "",
) -> str:
    """Wrap section HTML in a complete email-safe HTML document.

    Parameters
    ----------
    body_html : str
        Pre-built section HTML (tables, divs, cards — inserted as-is).
    title : str
        Bold header text on dark banner. If empty, no banner is rendered.
    subtitle : str
        Lighter text below the title on the banner.
    footer_text : str
        Attribution line in the footer.
    max_width : int
        Max width of the email container in pixels.
    notes_html : str
        Optional HTML rendered below the bordered box but above the footer.

    Returns
    -------
    str
        Complete ``<!DOCTYPE html>`` document ready for email delivery.
    """
    # Header banner (only if title provided)
    header_html = ""
    if title:
        sub_html = ""
        if subtitle:
            sub_html = (f'<p style="margin:6px 0 0; font-size:14px; '
                        f'color:#94a3b8; font-family:{FONT};">{subtitle}</p>')
        header_html = f'''
    <div style="background-color:{CLR_HEADER}; color:#fff; padding:24px 28px;
                border-radius:8px 8px 0 0;">
      <h1 style="margin:0; font-size:22px; font-weight:700;
                 color:{CLR_WHITE}; font-family:{FONT};">{title}</h1>
      {sub_html}
    </div>'''

    # Footer
    now = datetime.now().strftime("%A, %B %d, %Y %I:%M %p")
    footer_html = f'''
    <div style="margin-top:24px; padding-top:12px;
                border-top:1px solid {CLR_BORDER};
                font-size:11px; color:{CLR_MUTED};">
      {footer_text}<br>
      {now}
    </div>'''

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:{CLR_BG}; font-family:{FONT};">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding:20px 10px;">
        <div style="max-width:{max_width}px; margin:0 auto;">
          {header_html}
          <div style="background-color:{CLR_WHITE}; padding:24px 28px;
                      {('border-radius:0 0 8px 8px;' if title else 'border-radius:8px;')}
                      border:2px solid {CLR_BORDER}; text-align:left;">
            {body_html}
          </div>
          {notes_html}
          {footer_html}
        </div>
      </td>
    </tr>
  </table>
</body>
</html>'''


# ---------------------------------------------------------------------------
# Email Delivery
# ---------------------------------------------------------------------------

def send_email(subject: str, html_body: str,
               to_addr: Optional[str] = None) -> bool:
    """Send an HTML email via Gmail SMTP using existing credentials.

    Uses the same Gmail address + app password as the IMAP client.
    Recipient defaults to STANLEY_EMAIL_TO env var, then GMAIL_ADDRESS.
    """
    from .imap_client import get_credentials

    gmail_addr, gmail_pass = get_credentials()

    if not to_addr:
        to_addr = os.environ.get("STANLEY_EMAIL_TO", gmail_addr)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Stanley <{gmail_addr}>"
    msg["To"] = to_addr

    text_part = MIMEText(
        "This report requires an HTML-capable email client.\n"
        "Generated by Stanley | NennerEngine",
        "plain", "utf-8"
    )
    html_part = MIMEText(html_body, "html", "utf-8")

    msg.attach(text_part)
    msg.attach(html_part)

    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
            server.starttls()
            server.login(gmail_addr, gmail_pass)
            server.send_message(msg)
        log.info(f"Email sent to {to_addr}: {subject}")
        return True
    except Exception as e:
        log.error(f"Email send failed: {e}")
        return False


# ---------------------------------------------------------------------------
# Markdown → HTML Converter
# ---------------------------------------------------------------------------

def markdown_to_html(md_text: str) -> str:
    """Convert a markdown report to a styled HTML email.

    Supports: ``# H1``, ``## H2``, ``### H3``, ``**bold**``,
    ``- bullet``, and ``| pipe | tables |``.

    Returns a complete HTML document via ``wrap_document()``.
    """
    # Escape HTML entities in the raw text
    body = md_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    lines = body.split("\n")
    html_lines: list[str] = []
    in_table = False
    is_header_row = True

    for line in lines:
        stripped = line.strip()

        # Table separator row (---|---|---)
        if re.match(r"^\|[\s\-:|]+\|$", stripped):
            continue

        # Table row
        if stripped.startswith("|") and stripped.endswith("|"):
            if not in_table:
                html_lines.append('<table style="width:100%; border-collapse:collapse; '
                                  f'margin:12px 0; font-size:13px; color:{CLR_TEXT};">')
                in_table = True
                is_header_row = True

            cells = [c.strip() for c in stripped.strip("|").split("|")]
            tag = "th" if is_header_row else "td"

            if is_header_row:
                style = (f'background:{CLR_ROW_ALT}; color:{CLR_TEXT}; '
                         f'padding:8px 10px; text-align:left; '
                         f'border:1px solid {CLR_BORDER}; font-weight:600;')
            else:
                style = (f'padding:6px 10px; border:1px solid {CLR_BORDER}; '
                         f'color:{CLR_TEXT};')

            row = "".join(f'<{tag} style="{style}">{c}</{tag}>' for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
            if is_header_row:
                is_header_row = False
        else:
            if in_table:
                html_lines.append("</table>")
                in_table = False
                is_header_row = True

            # Horizontal rule (---)
            if re.match(r"^-{3,}$", stripped):
                html_lines.append(
                    f'<hr style="border:none; border-top:2px solid {CLR_BORDER}; '
                    f'margin:8px 0;">')
            # Headers
            elif stripped.startswith("### "):
                html_lines.append(
                    f'<h3 style="color:{CLR_TEXT}; font-size:15px; '
                    f'margin:10px 0 4px 0;">{stripped[4:]}</h3>')
            elif stripped.startswith("## "):
                html_lines.append(
                    f'<h2 style="color:{CLR_HEADER}; font-size:18px; '
                    f'margin:12px 0 4px 0;">{stripped[3:]}</h2>')
            elif stripped.startswith("# "):
                html_lines.append(
                    f'<h1 style="color:{CLR_HEADER}; font-size:22px; '
                    f'margin:12px 0 6px 0; border-bottom:1px solid {CLR_BORDER}; '
                    f'padding-bottom:6px;">{stripped[2:]}</h1>')
            elif stripped.startswith("- "):
                content = stripped[2:]
                content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
                html_lines.append(
                    f'<li style="color:{CLR_TEXT}; font-size:14px; '
                    f'line-height:1.5; margin:1px 0;">{content}</li>')
            elif stripped == "":
                continue  # skip blank lines instead of adding <br>
            else:
                content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
                html_lines.append(
                    f'<p style="color:{CLR_TEXT}; font-size:14px; '
                    f'line-height:1.6; margin:4px 0;">{content}</p>')

    if in_table:
        html_lines.append("</table>")

    body_html = "\n".join(html_lines)
    return wrap_document(body_html)
