"""Tests for postmaster email formatting module."""

import unittest

from nenner_engine.postmaster import wrap_document, markdown_to_html


class TestWrapDocument(unittest.TestCase):
    """Test the HTML document shell builder."""

    def test_returns_valid_html_doctype(self):
        html = wrap_document("<p>Hello</p>")
        self.assertTrue(html.strip().startswith("<!DOCTYPE html>"))

    def test_body_content_included(self):
        html = wrap_document("<p>Test body</p>")
        self.assertIn("Test body", html)

    def test_title_rendered(self):
        html = wrap_document("<p>Content</p>", title="My Report")
        self.assertIn("My Report", html)

    def test_subtitle_rendered(self):
        html = wrap_document("<p>Content</p>", title="T", subtitle="Feb 28")
        self.assertIn("Feb 28", html)

    def test_no_title_no_banner(self):
        html = wrap_document("<p>Content</p>", title="")
        # border-radius:8px (no banner split) should appear
        self.assertIn("border-radius:8px", html)

    def test_default_footer_text(self):
        html = wrap_document("<p>Content</p>")
        self.assertIn("Generated by Stanley", html)

    def test_custom_footer_text(self):
        html = wrap_document("<p>Content</p>", footer_text="Custom Footer")
        self.assertIn("Custom Footer", html)

    def test_no_charles_nenner_in_output(self):
        html = wrap_document("<p>Content</p>", title="Report")
        self.assertNotIn("Charles Nenner", html)

    def test_no_vartanian_capital_in_output(self):
        html = wrap_document("<p>Content</p>", title="Report")
        self.assertNotIn("Vartanian Capital", html)

    def test_notes_html_included(self):
        html = wrap_document("<p>Body</p>", notes_html="<p>Notes here</p>")
        self.assertIn("Notes here", html)


class TestMarkdownToHtml(unittest.TestCase):
    """Test markdown-to-HTML conversion."""

    def test_heading_h1(self):
        html = markdown_to_html("# Main Title")
        self.assertIn("<h1", html)
        self.assertIn("Main Title", html)

    def test_heading_h2(self):
        html = markdown_to_html("## Section")
        self.assertIn("<h2", html)
        self.assertIn("Section", html)

    def test_heading_h3(self):
        html = markdown_to_html("### Subsection")
        self.assertIn("<h3", html)
        self.assertIn("Subsection", html)

    def test_bold_text(self):
        html = markdown_to_html("This is **bold** text")
        self.assertIn("<strong>bold</strong>", html)

    def test_bullet_list(self):
        html = markdown_to_html("- Item one\n- Item two")
        self.assertIn("<li", html)
        self.assertIn("Item one", html)
        self.assertIn("Item two", html)

    def test_table(self):
        md = "| A | B |\n|---|---|\n| 1 | 2 |"
        html = markdown_to_html(md)
        self.assertIn("<table", html)
        self.assertIn("<th", html)
        self.assertIn("<td", html)

    def test_empty_input(self):
        html = markdown_to_html("")
        self.assertIn("<!DOCTYPE html>", html)

    def test_returns_complete_document(self):
        html = markdown_to_html("# Test")
        self.assertIn("<!DOCTYPE html>", html)
        self.assertIn("</html>", html)

    def test_html_entities_escaped(self):
        html = markdown_to_html("Price < 100 & value > 50")
        self.assertIn("&lt;", html)
        self.assertIn("&gt;", html)
        self.assertIn("&amp;", html)


if __name__ == "__main__":
    unittest.main()
